name: 'execute user code in an EIC environment'
description: 'Spawns appropriate docker image and executes user code in the environment of a specified EIC shell'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  organization:
    description: 'EIC shell organization you are targeting (e.g. eic)'
    required: false
    default: 'eicweb'
  platform:
    description: 'EIC shell platform you are targeting (e.g. eic_xl)'
    required: false
    default: ''
  release:
    description: 'EIC shell release you are targeting (e.g. 3.0-stable)'
    required: false
    default: ''
  platform-release:
    description: 'EIC shell release platform string you are targeting (e.g. eic_xl:24.11.2-stable)'
    required: false
    default: ''
  run:
    description: 'They payload code you want to execute on top of the view'
    required: false
    default: ''
  setup:
    description: 'Environment initialization bash script that is sourced (e.g. install/bin/thisepic.sh)'
    required: false
    default: ''
  sandbox-path:
    description: 'Custom path where the sandbox is located'
    required: false
    default: ''
  apptainer_version:
    description: 'Apptainer version to use (e.g. v1.4.5 or latest)'
    required: false
    default: 'v1.4.5'
  apptainer_deb_cache:
    description: 'Location (directory) of the cached apptainer deb.'
    required: false
    default: 'apptainer_deb_cache'

runs:
  using: "composite"
  steps:
    - name: Restore cached apptainer package
      id: cache-restore
      uses: actions/cache@v4
      with:
        key: apptainer-deb-cache-${{ inputs.apptainer_version }}
        path: |
          ${{ inputs.apptainer_deb_cache }}
    - name: Run inside eic-shell
      id: run-eic-shell
      run: |
        ${{ github.action_path }}/setup-eic-shell.sh
      shell: bash
      env:
        THIS: ${{ github.action_path }}
        GITHUB_ACTOR: ${{ github.actor }}
        EIC_SHELL_ORGANIZATION: ${{ inputs.organization }}
        EIC_SHELL_RELEASE: ${{ inputs.release }}
        EIC_SHELL_PLATFORM_RELEASE: ${{ inputs.platform-release }}
        EIC_SHELL_PLATFORM: ${{ inputs.platform }}
        RUN: ${{ inputs.run }}
        SETUP: ${{ inputs.setup }}
        SANDBOX_PATH: ${{ inputs.sandbox-path }}
        APPTAINER_DEB_CACHE: ${{ inputs.apptainer_deb_cache }}
        APPTAINER_VERSION: ${{ inputs.apptainer_version }}
    - name: Store apptainer package to cache
      uses: actions/cache/save@v4
      if: steps.run-eic-shell.outputs.cache-update == 'true'      
      with:
        key: apptainer-deb-cache-${{ inputs.apptainer_version }}
        path: |
          ${{ inputs.apptainer_deb_cache }}
