name: 'execute user code in an EIC environment'
description: 'Spawns appropriate docker image and executes user code in the environment of a specified EIC shell'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  container:
    description: 'Which container to use as base to setup a view. By default the container is inferred from `view-path` (default: `auto`)'
    required: false
    default: 'auto'
  platform:
    description: 'EIC shell platform you are targeting (e.g. jug_xl)'
    required: false
    default: ''
  release:
    description: 'EIC shell release you are targeting (e.g. 3.0-stable)'
    required: false
    default: ''
  platform-release:
    description: 'LCG view release platform string you are targeting (e.g. jug_xl:3.0-stable)'
    required: false
    default: ''
  run:
    description: 'They payload code you want to execute on top of the view'
    required: false
    default: ''
  run_local_checkout:
    description: 'Run the local checkout of the action and not the main repo code'
    required: false
    default: 'false'
  setup-script:
    description: 'Initialization/setup script for a shell that sets the environment (e.g. /opt/detector/setup.sh)'
    required: false
    default: '/opt/detector/setup.sh'
  sandbox-path:
    description: 'Custom path where the sandbox is located'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - run: |
        if [ "${{ inputs.run_local_checkout }}" == "true" ]; then
          echo "WARNING running local checkout of the action !"
          .  setup-eic-shell.sh local
        else
          ${{ github.action_path }}/setup-eic-shell.sh
        fi
      shell: bash
      env:
        THIS: ${{ github.action_path }}
        CONTAINER: ${{ inputs.container }}
        GITHUB_ACTOR: ${{ github.actor }}
        EIC_SHELL_RELEASE: ${{ inputs.release }}
        EIC_SHELL_PLATFORM_RELEASE: ${{ inputs.platform-release }}
        EIC_SHELL_PLATFORM: ${{ inputs.platform }}
        RUN: ${{ inputs.run }}
        SETUP_SCRIPT: ${{ inputs.setup-script }}
        SANDBOX_PATH: ${{ inputs.sandbox-path }}
