name: 'execute user code in an EIC environment'
description: 'Spawns appropriate docker image and executes user code in the environment of a specified EIC shell'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  platform:
    description: 'EIC shell platform you are targeting (e.g. jug_xl)'
    required: false
    default: ''
  release:
    description: 'EIC shell release you are targeting (e.g. 3.0-stable)'
    required: false
    default: ''
  platform-release:
    description: 'EIC shell release platform string you are targeting (e.g. jug_xl:3.0-stable)'
    required: false
    default: ''
  run:
    description: 'They payload code you want to execute on top of the view'
    required: false
    default: ''
  setup:
    description: 'Environment initialization bash script that is sourced (e.g. install/setup.sh)'
    required: false
    default: ''
  sandbox-path:
    description: 'Custom path where the sandbox is located'
    required: false
    default: ''
  network_types:
    description: 'Network access types inside EIC shell'
    required: false
    default: 'bridge'

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/setup-eic-shell.sh
      shell: bash
      env:
        THIS: ${{ github.action_path }}
        GITHUB_ACTOR: ${{ github.actor }}
        EIC_SHELL_RELEASE: ${{ inputs.release }}
        EIC_SHELL_PLATFORM_RELEASE: ${{ inputs.platform-release }}
        EIC_SHELL_PLATFORM: ${{ inputs.platform }}
        RUN: ${{ inputs.run }}
        SETUP: ${{ inputs.setup }}
        SANDBOX_PATH: ${{ inputs.sandbox-path }}
        NETWORK_TYPES: ${{ inputs.network_types }}
